<?
$PERM["Exit.png"]["2"]="X";
$PERM["Exit.png"]["3"]="X";
$PERM["Exit.png"]["4"]="X";
$PERM["Exit.png"]["5"]="X";
$PERM["Exit.png"]["6"]="X";
$PERM["Exit.png"]["7"]="X";
$PERM["Exit.png"]["8"]="X";
$PERM["Exit.png"]["9"]="X";
$PERM["Exit.png"]["*"]="X";
?>