<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
    $APPLICATION->SetTitle("Каталог");
?>
<?$APPLICATION->IncludeComponent(
    "bitrix:catalog",
    "main_catalog",
    Array(
        "IBLOCK_TYPE" => "OSG_WEB_SHOP",
        "IBLOCK_ID" => "88",
        "HIDE_NOT_AVAILABLE" => "N",
        "BASKET_URL" => "/personal/basket/",
        "ACTION_VARIABLE" => "action",
        "PRODUCT_ID_VARIABLE" => "id",
        "SECTION_ID_VARIABLE" => "SECTION_ID",
        "PRODUCT_QUANTITY_VARIABLE" => "quantity",
        "PRODUCT_PROPS_VARIABLE" => "prop",
        "SEF_MODE" => "Y",
        "SEF_FOLDER" => "/catalog/",
        "AJAX_MODE" => "N",
        "AJAX_OPTION_JUMP" => "N",
        "AJAX_OPTION_STYLE" => "Y",
        "AJAX_OPTION_HISTORY" => "N",
        "CACHE_TYPE" => "A",
        "CACHE_TIME" => "36000000",
        "CACHE_FILTER" => "N",
        "CACHE_GROUPS" => "N",
        "SET_TITLE" => "Y",
        "SET_STATUS_404" => "N",
        "USE_ELEMENT_COUNTER" => "Y",
        "USE_FILTER" => "N",
        "USE_REVIEW" => "N",
        "USE_COMPARE" => "Y",
        "COMPARE_NAME" => "CATALOG_COMPARE_LIST",
        "COMPARE_FIELD_CODE" => array(0=>"",1=>"",),
        "COMPARE_PROPERTY_CODE" => array(0=>"FIRM",1=>"WARRANTY",2=>"",),
        "COMPARE_ELEMENT_SORT_FIELD" => "sort",
        "COMPARE_ELEMENT_SORT_ORDER" => "asc",
        "DISPLAY_ELEMENT_SELECT_BOX" => "N",
        "PRICE_CODE" => array(
            0=>$_GLOBALS["SITE_VARIABLES"]["PRICE_CODE"],          
        ),
        "USE_PRICE_COUNT" => "N",
        "SHOW_PRICE_COUNT" => "1",
        "PRICE_VAT_INCLUDE" => "Y",
        "PRICE_VAT_SHOW_VALUE" => "N",
        "PRODUCT_PROPERTIES" => array(),
        "USE_PRODUCT_QUANTITY" => "Y",
        "CONVERT_CURRENCY" => "Y",
        "CURRENCY_ID" => "RUR",
        "SHOW_TOP_ELEMENTS" => "N",
        "SECTION_COUNT_ELEMENTS" => "Y",
        "SECTION_TOP_DEPTH" => "1",
        "PAGE_ELEMENT_COUNT" => "100",
        "LINE_ELEMENT_COUNT" => "1",
        "ELEMENT_SORT_FIELD" => "sort",
        "ELEMENT_SORT_ORDER" => "asc",
        "ELEMENT_SORT_FIELD2" => "id",
        "ELEMENT_SORT_ORDER2" => "desc",
        "LIST_PROPERTY_CODE" => array(0=>"FIRM",1=>"COUNTRY",2=>"STATUS",3=>"DESCRIPTION",4=>"UNC",5=>"UNIT",6=>"SIZE",7=>"EXPIRED",8=>"WARRANTY",9=>"WEIGHT",10=>"CONSIGNMEN",11=>"RESERV",12=>"MAX_ORDER",13=>"OPT_QUANTITY",14=>"OPT_QUANTITY_INC",15=>"OPT_PRICE",16=>"OPT_PRICE_INC",17=>"SPEC_OFFER",18=>"ADD_GOODS",19=>"ADD_IMAGES",20=>"MAIN_SECTION",21=>"",),
        "INCLUDE_SUBSECTIONS" => "Y",
        "LIST_META_KEYWORDS" => "-",
        "LIST_META_DESCRIPTION" => "-",
        "LIST_BROWSER_TITLE" => "-",
        "DETAIL_PROPERTY_CODE" => array(0=>"FIRM",1=>"COUNTRY",2=>"STATUS",3=>"DESCRIPTION",4=>"UNC",5=>"UNIT",6=>"SIZE",7=>"EXPIRED",8=>"WARRANTY",9=>"WEIGHT",10=>"CONSIGNMEN",11=>"RESERV",12=>"MAX_ORDER",13=>"OPT_QUANTITY",14=>"OPT_QUANTITY_INC",15=>"OPT_PRICE",16=>"OPT_PRICE_INC",17=>"SPEC_OFFER",18=>"ADD_GOODS",19=>"ADD_IMAGES",20=>"H1",21=>"TITLE",22=>"KEYWORDS",23=>"MAIN_SECTION",24=>"DESCRIPTION2",25=>"",),
        "DETAIL_META_KEYWORDS" => "-",
        "DETAIL_META_DESCRIPTION" => "-",
        "DETAIL_BROWSER_TITLE" => "-",
        "LINK_IBLOCK_TYPE" => "",
        "LINK_IBLOCK_ID" => "",
        "LINK_PROPERTY_SID" => "",
        "LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
        "USE_ALSO_BUY" => "N",
        "USE_STORE" => "Y",
        "USE_STORE_PHONE" => "N",
        "USE_STORE_SCHEDULE" => "N",
        "USE_MIN_AMOUNT" => "Y",
        "MIN_AMOUNT" => "1",
        "STORE_PATH" => "/store/#store_id#",
        "MAIN_TITLE" => "Наличие на складах",
        "PAGER_TEMPLATE" => "catalog",
        "DISPLAY_TOP_PAGER" => "N",
        "DISPLAY_BOTTOM_PAGER" => "Y",
        "PAGER_TITLE" => "Товары",
        "PAGER_SHOW_ALWAYS" => "Y",
        "PAGER_DESC_NUMBERING" => "N",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
        "PAGER_SHOW_ALL" => "Y",
        "OFFERS_FIELDS" => array(0=>"NAME",1=>"",),
        "OFFERS_PROPERTIES" => array(0=>"",1=>"",),
        "AJAX_OPTION_ADDITIONAL" => "",
        "ADD_SECTIONS_CHAIN" => "Y",
        "ADD_ELEMENT_CHAIN" => "Y",
        "ADD_PROPERTIES_TO_BASKET" => "Y",
        "PARTIAL_PRODUCT_PROPERTIES" => "N",
        "SECTIONS_VIEW_MODE" => "LIST",
        "SECTIONS_SHOW_PARENT_NAME" => "Y",
        "DETAIL_DISPLAY_NAME" => "Y",
        "DETAIL_DETAIL_PICTURE_MODE" => "IMG",
        "DETAIL_ADD_DETAIL_TO_SLIDER" => "N",
        "DETAIL_DISPLAY_PREVIEW_TEXT_MODE" => "E",
        "TEMPLATE_THEME" => "blue",
        "ADD_PICT_PROP" => "-",
        "LABEL_PROP" => "-",
        "SHOW_DISCOUNT_PERCENT" => "N",
        "SHOW_OLD_PRICE" => "N",
        "DETAIL_SHOW_MAX_QUANTITY" => "N",
        "MESS_BTN_BUY" => "Купить",
        "MESS_BTN_ADD_TO_BASKET" => "В корзину",
        "MESS_BTN_COMPARE" => "Сравнение",
        "MESS_BTN_DETAIL" => "Подробнее",
        "MESS_NOT_AVAILABLE" => "Нет в наличии",
        "DETAIL_USE_VOTE_RATING" => "N",
        "DETAIL_USE_COMMENTS" => "N",
        "USE_SALE_BESTSELLERS" => "Y",
        "FILTER_VIEW_MODE" => "VERTICAL",
        "SEF_URL_TEMPLATES" => Array(
            "sections" => "",
            "section" => "#SECTION_ID#/",
            "element" => "#SECTION_ID#/#ELEMENT_ID#/",
            "compare" => "test.php?action=#ACTION_CODE#"
        ),
        "VARIABLE_ALIASES" => Array(
            "section" => Array(),
            "element" => Array(),
            "compare" => Array(
                "ACTION_CODE" => "action"
            ),
            "sections" => Array(),
        )
    )
    );?> <?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>